# Generated by Django 3.1.6 on 2021-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20210310_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='client.ico', upload_to='profile_pics'),
        ),
    ]
